export enum ACTION_KEY_ENUM {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  SEND_SIGNATURE_REQUEST = 'SEND_SIGNATURE_REQUEST',
  SIGN = 'SIGN',
  APPROVE = 'APPROVE',
  INVITE = 'INVITE',
  MANAGE = 'MANAGE',
  REMOVE = 'REMOVE',
  CANCEL = 'CANCEL',
}
