export enum EmailSubject {
  DOCUMENT_PENDING = 'Firma de documentos',
  DOCUMENT_SIGNED = 'Documento firmado exitosamente',
  DOCUMENT_REJECTED = 'Documento rechazado',
  CANCELLATION_PENDING = 'Solicitud de cancelación de documento',
  DOCUMENT_CANCELLED = 'Documento cancelado',
  VERIFICATION_CODE = 'Código de verificación',
  PASSWORD_RESET_OTP = 'Recupera tu contraseña',
  REGISTRATION_OTP = 'Verifica tu correo',
  ORGANIZATION_INVITATION = 'Te invitaron a una organización',
  DOCUMENT_INVITATION = 'Te invitaron a firmar un documento',
  DOCUMENT_WITNESS_ADDED = 'Te agregaron como testigo de un documento',
  DOCUMENT_APPROVAL_REQUESTED = 'Tienes un documento pendiente de aprobación',
  ORGANIZATION_MEMBER_JOINED = 'Nuevo miembro en tu organización',
}
