export enum FILE_STATUS_ENUM{
    FILE_FOUND = 'FILE_FOUND',
    FILE_NOT_FOUND = 'FILE_NOT_FOUND',
    FILE_CREATED = 'FILE_CREATED',
    FILE_OVERWRITTEN = 'FILE_OVERWRITTEN',
    FILE_DELETED = 'FILE_DELETED'
}