name: Continuous Deployment Development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Build Image & Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          no-cache: true
          tags: |
            dataloplatforms/signature-server:latest
            dataloplatforms/signature-server:${{ github.sha }}

      - name: Actualizar contenedor en el Servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Conectado al servidor de desarrollo $(curl -s ifconfig.me)"
             cd /root/signature-development

             echo "Descargando la última versión de la imagen desde Docker Hub"
             docker compose pull backend

             echo "Recreando el contenedor de signature-backend-dev (Actualizando versión)"
             docker compose up -d --remove-orphans backend

             echo "Limpiando imágenes huérfanas en el servidor para liberar espacio"
             docker image prune -f

             echo "¡Despliegue completado con éxito en el servidor!"
